(function() {var implementors = {};
implementors["sitemap"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"sitemap/structs/struct.UrlEntry.html\" title=\"struct sitemap::structs::UrlEntry\">UrlEntry</a>&gt; for <a class=\"struct\" href=\"sitemap/structs/struct.UrlEntryBuilder.html\" title=\"struct sitemap::structs::UrlEntryBuilder\">UrlEntryBuilder</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"sitemap/structs/struct.UrlEntry.html\" title=\"struct sitemap::structs::UrlEntry\">UrlEntry</a>&gt; for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/string/struct.String.html\" title=\"struct alloc::string::String\">String</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"sitemap/structs/struct.UrlEntry.html\" title=\"struct sitemap::structs::UrlEntry\">UrlEntry</a>&gt; for &amp;'static <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"sitemap/structs/struct.SiteMapEntry.html\" title=\"struct sitemap::structs::SiteMapEntry\">SiteMapEntry</a>&gt; for <a class=\"struct\" href=\"sitemap/structs/struct.SiteMapEntryBuilder.html\" title=\"struct sitemap::structs::SiteMapEntryBuilder\">SiteMapEntryBuilder</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"sitemap/structs/struct.SiteMapEntry.html\" title=\"struct sitemap::structs::SiteMapEntry\">SiteMapEntry</a>&gt; for <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/string/struct.String.html\" title=\"struct alloc::string::String\">String</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"struct\" href=\"sitemap/structs/struct.SiteMapEntry.html\" title=\"struct sitemap::structs::SiteMapEntry\">SiteMapEntry</a>&gt; for &amp;'static <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.str.html\">str</a>",];
implementors["unicode_bidi"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.Into.html\" title=\"trait core::convert::Into\">Into</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u8.html\">u8</a>&gt; for <a class=\"struct\" href=\"unicode_bidi/level/struct.Level.html\" title=\"struct unicode_bidi::level::Level\">Level</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
